
# Develop LSTM = long short term memory network for univariate Time Series Forecasting

In [4]:
pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 2.1 MB/s eta 0:00:00
     -------------------------------------- 57.5/57.5 kB 116.3 kB/s eta 0:00:00
     ------------------------------------ 126.5/126.5 kB 573.0 kB/s eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 9.3 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 7.9 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 5.4 MB/s eta 0:00:00
     -------------------------------------- 439.2/439.2 kB 2.7 MB/s eta 0:00:00
     -------------------------------------- 895.9/895.9 kB 4.0 MB/s eta 0:00:00
     ---------------------------------------- 23.2/23.2 MB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 7.2 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 1.7 MB/s eta 0:00:00
     -------------------------------------- 177.2/177.2 kB 2.7 MB/s eta 0:00:00
     -------------------------------------- 781.

In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [6]:
# preparing independent and dependent variables
def prepare_data(timeseries_data, n_features):
  X, y = [], []
  for i in range(len(timeseries_data)):
    # find the end of this pattern
    end_ix = i + n_features
    # check if we are beyond the sequence 
    if end_ix > len(timeseries_data)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

In [7]:
# define number sequence
timeseries_data = [100, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps=3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [8]:
print(X), print(y)

[[100 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [9]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [10]:
X.shape

(6, 3, 1)

In [11]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences = True, input_shape = (n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
#fit model
model.fit(X,y, epochs = 300, verbose = 1)

Epoch 1/300
1/1 [==============================] - 7s 7s/step - loss: 33132.4453
Epoch 2/300
1/1 [==============================] - 0s 12ms/step - loss: 32613.9609
Epoch 3/300
1/1 [==============================] - 0s 14ms/step - loss: 32082.8691
Epoch 4/300
1/1 [==============================] - 0s 12ms/step - loss: 31558.5254
Epoch 5/300
1/1 [==============================] - 0s 13ms/step - loss: 31062.3145
Epoch 6/300
1/1 [==============================] - 0s 15ms/step - loss: 30601.5469
Epoch 7/300
1/1 [==============================] - 0s 14ms/step - loss: 30163.3535
Epoch 8/300
1/1 [==============================] - 0s 16ms/step - loss: 29733.0781
Epoch 9/300
1/1 [==============================] - 0s 16ms/step - loss: 29291.0645
Epoch 10/300
1/1 [==============================] - 0s 18ms/step - loss: 28810.3594
Epoch 11/300
1/1 [==============================] - 0s 16ms/step - loss: 28272.7012
Epoch 12/300
1/1 [==============================] - 0s 21ms/step - loss: 27654.6465
Epo

1/1 [==============================] - 0s 15ms/step - loss: 13.5659
Epoch 101/300
1/1 [==============================] - 0s 13ms/step - loss: 12.7898
Epoch 102/300
1/1 [==============================] - 0s 13ms/step - loss: 12.1183
Epoch 103/300
1/1 [==============================] - 0s 13ms/step - loss: 11.3003
Epoch 104/300
1/1 [==============================] - 0s 12ms/step - loss: 10.5145
Epoch 105/300
1/1 [==============================] - 0s 14ms/step - loss: 9.7310
Epoch 106/300
1/1 [==============================] - 0s 13ms/step - loss: 9.2586
Epoch 107/300
1/1 [==============================] - 0s 13ms/step - loss: 8.6140
Epoch 108/300
1/1 [==============================] - 0s 12ms/step - loss: 8.1131
Epoch 109/300
1/1 [==============================] - 0s 14ms/step - loss: 7.8815
Epoch 110/300
1/1 [==============================] - 0s 17ms/step - loss: 7.3017
Epoch 111/300
1/1 [==============================] - 0s 15ms/step - loss: 6.9820
Epoch 112/300
1/1 [==================

1/1 [==============================] - 0s 15ms/step - loss: 2.8730
Epoch 202/300
1/1 [==============================] - 0s 14ms/step - loss: 2.8787
Epoch 203/300
1/1 [==============================] - 0s 15ms/step - loss: 2.9255
Epoch 204/300
1/1 [==============================] - 0s 14ms/step - loss: 2.9941
Epoch 205/300
1/1 [==============================] - 0s 15ms/step - loss: 3.0018
Epoch 206/300
1/1 [==============================] - 0s 16ms/step - loss: 2.8060
Epoch 207/300
1/1 [==============================] - 0s 15ms/step - loss: 2.7872
Epoch 208/300
1/1 [==============================] - 0s 15ms/step - loss: 2.8964
Epoch 209/300
1/1 [==============================] - 0s 15ms/step - loss: 2.7861
Epoch 210/300
1/1 [==============================] - 0s 13ms/step - loss: 2.7187
Epoch 211/300
1/1 [==============================] - 0s 16ms/step - loss: 2.7989
Epoch 212/300
1/1 [==============================] - 0s 14ms/step - loss: 2.7390
Epoch 213/300
1/1 [=======================

In [15]:
# demonstrate prediction for next 10 days
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1

[217.35133]
1 day input [196.         210.         217.35133362]
1 day output [[228.26642]]
2 day input [210.         217.35133362 228.26641846]
2 day output [[235.84247]]
3 day input [217.35133 228.26642 235.84247]
3 day output [[244.75388]]
4 day input [228.26642 235.84247 244.75388]
4 day output [[252.77475]]
5 day input [235.84247 244.75388 252.77475]
5 day output [[260.78766]]
6 day input [244.75388 252.77475 260.78766]
6 day output [[268.79507]]
7 day input [252.77475 260.78766 268.79507]
7 day output [[276.61554]]
8 day input [260.78766 268.79507 276.61554]
8 day output [[284.4669]]
9 day input [268.79507 276.61554 284.4669 ]
9 day output [[292.29343]]
